#!/bin/bash

# Setup script for GitHub Actions secrets
# This script helps you set up the required secrets for the monthly poll workflow

echo "🔧 GitHub Actions Secrets Setup"
echo "==============================="
echo ""

echo "This script will help you set up the required secrets for the monthly poll workflow."
echo "You'll need to add these secrets to your GitHub repository manually."
echo ""

echo "📋 Required Secrets:"
echo "==================="
echo ""

echo "1. TELEGRAM_BOT_TOKEN"
echo "   - Your main Telegram bot token (for event notifications)"
echo "   - Get this from @BotFather on Telegram"
echo "   - Format: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz"
echo ""

echo "2. TELEGRAM_CHAT_ID"
echo "   - The main chat ID for event notifications"
echo "   - For group chats: Use @userinfobot to get the chat ID"
echo "   - For private chats: Use @userinfobot to get your user ID"
echo "   - Format: -1001234567890 (for groups) or 123456789 (for users)"
echo ""

echo "3. TELEGRAM_POLL_BOT_TOKEN"
echo "   - Your separate Telegram bot token (for polls)"
echo "   - Create a second bot with @BotFather on Telegram"
echo "   - Format: 987654321:XYZabcDEFghiJKLmnopqrsTUVwxyz"
echo ""

echo "4. TELEGRAM_POLL_CHAT_ID"
echo "   - The chat ID where polls should be sent"
echo "   - For group chats: Use @userinfobot to get the chat ID"
echo "   - For private chats: Use @userinfobot to get your user ID"
echo "   - Format: -1001234567890 (for groups) or 123456789 (for users)"
echo ""

echo "🔗 How to get Chat ID:"
echo "====================="
echo "1. Add @userinfobot to your chat"
echo "2. Send any message to the chat"
echo "3. The bot will reply with the chat ID"
echo "4. Copy the chat ID (it's a number, may be negative for groups)"
echo ""

echo "📝 How to add secrets to GitHub:"
echo "==============================="
echo "1. Go to your repository on GitHub"
echo "2. Click on 'Settings' tab"
echo "3. Click on 'Secrets and variables' → 'Actions'"
echo "4. Click 'New repository secret'"
echo "5. Add each secret with the exact name and value"
echo ""

echo "🧪 Testing the setup:"
echo "===================="
echo "1. After adding secrets, go to the 'Actions' tab"
echo "2. Find 'Monthly Meetup Poll Scheduler' workflow"
echo "3. Click 'Run workflow'"
echo "4. Enable 'Test mode' and click 'Run workflow'"
echo "5. Check the logs to ensure everything works"
echo ""

echo "📊 Workflow Schedule:"
echo "===================="
echo "The monthly poll workflow will run:"
echo "- Automatically on the 20th of every month at 9:00 AM CST"
echo "- You can also trigger it manually anytime"
echo ""

echo "✅ Setup Checklist:"
echo "=================="
echo "□ TELEGRAM_BOT_TOKEN added to repository secrets"
echo "□ TELEGRAM_CHAT_ID added to repository secrets"
echo "□ TELEGRAM_POLL_BOT_TOKEN added to repository secrets"
echo "□ TELEGRAM_POLL_CHAT_ID added to repository secrets"
echo "□ Main bot added to the main chat with proper permissions"
echo "□ Poll bot added to the poll chat with proper permissions"
echo "□ Test run completed successfully"
echo ""

echo "🚀 Next Steps:"
echo "============="
echo "1. Add the secrets to your GitHub repository"
echo "2. Test the workflow manually with test mode enabled"
echo "3. Wait for the 20th of the month for automatic execution"
echo "4. Monitor the workflow runs in the Actions tab"
echo ""

echo "📚 Documentation:"
echo "================"
echo "For more details, see:"
echo "- GITHUB_ACTIONS_SETUP.md"
echo "- POLL_INTEGRATION.md"
echo ""

echo "❓ Need Help?"
echo "============"
echo "If you encounter issues:"
echo "1. Check the troubleshooting section in GITHUB_ACTIONS_SETUP.md"
echo "2. Verify bot permissions in Telegram"
echo "3. Test locally with ./test_github_actions.sh"
echo "4. Check GitHub Actions logs for error details"
echo ""

echo "Setup guide completed! 🎉"
